FROM pseudomuto/protoc-gen-doc AS generator

WORKDIR /usr/src/app

RUN apk add npm

RUN npm i @a11ywatch/protos

RUN mkdir ./doc && cp -R node_modules/@a11ywatch/protos proto

RUN protoc --doc_out=./doc --doc_opt=html,index.html proto/*.proto

FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN apk upgrade --update-cache --available && \
	apk add openssl && \
	rm -rf /var/cache/apk/*

RUN npm ci

COPY . .
COPY --from=generator /usr/src/app/doc ./public/protodoc

CMD ["node_modules/ts-node-dev/lib/bin.js", "--no-experimental-fetch", "--transpile-only", "-r", "tsconfig-paths/register", "src/server.ts"]