FROM pseudomuto/protoc-gen-doc AS generator

WORKDIR /usr/src/app

RUN apk add npm

RUN npm i @a11ywatch/protos@0.1.5

RUN mkdir ./doc && cp -R node_modules/@a11ywatch/protos proto

RUN protoc --doc_out=./doc --doc_opt=html,index.html proto/*.proto

FROM node:16-alpine3.14

WORKDIR /usr/src/app

COPY package*.json bootstrap.sh ./

RUN apk upgrade --update-cache --available && \
	apk add openssl && \
	rm -rf /var/cache/apk/*

RUN ./bootstrap.sh
RUN npm ci

COPY . .
COPY --from=generator /usr/src/app/doc ./protodoc

CMD [ "npm", "run", "dev" ]
