FROM node:16-alpine3.14

WORKDIR /usr/src/app

COPY package*.json bootstrap.sh ./

RUN apk upgrade --update-cache --available && \
	apk add openssl && \
	rm -rf /var/cache/apk/*

RUN ./bootstrap.sh
RUN npm ci

COPY . .

CMD [ "npm", "run", "dev" ]
